# Generated by Django 2.2.4 on 2019-08-29 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 13, 57, 928438))),
                ('quantity', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Plant')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Pond')),
            ],
        ),
        migrations.CreateModel(
            name='PondConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 13, 57, 928072))),
                ('level', models.FloatField()),
                ('purity', models.BooleanField(default=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Pond')),
            ],
        ),
        migrations.CreateModel(
            name='PlantConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 13, 57, 927665))),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soilMoisture', models.FloatField()),
                ('diseased', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Plant')),
            ],
        ),
    ]
