# Generated by Django 2.2.4 on 2019-08-27 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0015_auto_20190827_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 4, 47, 14, 271542))),
                ('quantity', models.FloatField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Plant')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Pond')),
            ],
        ),
        migrations.CreateModel(
            name='PondConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 4, 47, 14, 271187))),
                ('level', models.FloatField()),
                ('purity', models.FloatField(default=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Pond')),
            ],
        ),
        migrations.CreateModel(
            name='PlantConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 4, 47, 14, 270728))),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soilMoisture', models.FloatField()),
                ('diseased', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Plant')),
            ],
        ),
    ]
