# Generated by Django 2.2.4 on 2019-09-02 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20190902_0608'),
        ('conditions', '0002_auto_20190831_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 6, 8, 21, 328628)),
        ),
        migrations.AlterField(
            model_name='pondconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 6, 8, 21, 329026)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 6, 8, 21, 329384)),
        ),
        migrations.CreateModel(
            name='FishFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 9, 2, 6, 8, 21, 329787))),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Pond')),
            ],
        ),
    ]
