# Generated by Django 2.2.4 on 2019-09-07 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0012_auto_20190907_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuatoroverride',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fishfeeding',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 14, 22, 36, 657959)),
        ),
        migrations.AlterField(
            model_name='plantconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 14, 22, 36, 656783)),
        ),
        migrations.AlterField(
            model_name='pondconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 14, 22, 36, 657184)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 14, 22, 36, 657556)),
        ),
    ]
