# Generated by Django 2.2.4 on 2019-09-07 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0014_auto_20190907_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watering',
            name='quantity',
        ),
        migrations.AddField(
            model_name='watering',
            name='motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fishfeeding',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 23, 9, 56, 446134)),
        ),
        migrations.AlterField(
            model_name='plantconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 23, 9, 56, 444983)),
        ),
        migrations.AlterField(
            model_name='pondconditions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 23, 9, 56, 445378)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 23, 9, 56, 445738)),
        ),
    ]
