# Generated by Django 2.2.4 on 2019-08-25 07:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0002_auto_20190825_0601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='Greenhouse',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='warehouse',
            new_name='Greenhouse',
        ),
        migrations.RenameField(
            model_name='pond',
            old_name='warehouse',
            new_name='Greenhouse',
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 7, 20, 4, 916168)),
        ),
    ]
