# Generated by Django 2.2.4 on 2019-09-03 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20190902_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 6, 5, 20, 456559)),
        ),
    ]
