# Generated by Django 2.2.4 on 2019-08-25 07:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0005_auto_20190825_0721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greenhouse',
            new_name='Warehouse',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Greenhouse',
            new_name='Warehouse',
        ),
        migrations.RenameField(
            model_name='pond',
            old_name='Greenhouse',
            new_name='Warehouse',
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 7, 22, 29, 329684)),
        ),
    ]
