# Generated by Django 2.2.4 on 2019-09-06 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20190906_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 15, 39, 49, 249991)),
        ),
    ]
