# Generated by Django 2.2.4 on 2019-08-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20190825_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 7, 23, 49, 829933)),
        ),
    ]
