# Generated by Django 2.2.4 on 2019-09-07 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_auto_20190906_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 3, 40, 3, 607174)),
        ),
    ]
