# Generated by Django 2.2.4 on 2019-08-26 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_auto_20190825_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 15, 7, 45, 984485)),
        ),
    ]
