# Generated by Django 2.2.4 on 2019-08-26 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_auto_20190826_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pond',
            old_name='Warehouse',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 15, 48, 6, 602041)),
        ),
    ]
