# Generated by Django 2.2.4 on 2019-08-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_auto_20190826_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 15, 59, 16, 135274)),
        ),
    ]
