# Generated by Django 2.2.4 on 2019-09-07 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20190907_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 23, 9, 56, 444466)),
        ),
    ]
