# Generated by Django 2.2.4 on 2019-08-27 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20190826_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 4, 47, 14, 270200)),
        ),
    ]
